### ISSUE TITLE
功能请求：希望添加上下文消息处理能力

### ISSUE THREAD

**Issue by BaiHLiu** [Si-Huan/XZZ#40]
例如输入某命令后，用户可以连续发送n条消息，当服务端接收完毕后给出响应。类似运营商的“请输入手机号码，按#号键结束” ;)
这样一来，对于处理图片的应用会非常友好，特别是当用户使用iOS QQ而不是电脑端，无法在消息中嵌入图片的情况。
再次感谢作者的付出！

**Comment by sihuan** [comment]
🥲 这代码我很久没维护了，现在觉得这个框架也不适合再做复杂的拓展，问题中这种包含“会话”的 bot 框架也有不少了，做的都不错🤣
不过如果觉得其他框架太复杂繁琐的话，可以尝试给 xzz 添加对多条消息的支持功能，欢迎 pr😁

**Comment by BaiHLiu** [comment]
奥 方便的话，请帮我推荐一个支持会话的框架，这对我很重要，不尽感激～

**Comment by sihuan** [comment]
https://onebot.dev/ecosystem.html
这里面提到的 onebot SDK 部分都可以参考下
nonebot2 应该不错

**Comment by BaiHLiu** [comment]
好的，非常感谢！
